language: python
cache: pip

install:
  - pip install tox
script:
  - tox -v
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      echo "Decrypting gcs-service-account.json.enc";
      openssl aes-256-cbc -K $encrypted_12e75a453f27_key -iv $encrypted_12e75a453f27_iv -in gcs-service-account.json.enc -out gcs-service-account.json -d;
    else
      echo "Skipping decryption of gcs-service-account.json.enc"
    fi

jobs:
  fast_finish: true
  include:
    - { name: 'check', python: '3.7', env: TOXENV=check }
    - { name: 'lint', python: '3.7', env: TOXENV=lint }
    - { name: 'py35', python: '3.5', env: TOXENV=py35 }
    - { name: 'py36', python: '3.6', env: TOXENV=py36 }
    - { name: 'py37', python: '3.7', env: TOXENV=py37 }
    - { name: 'py38', python: '3.8', env: TOXENV=py38 }
    - { name: 'docs', python: '3.7', env: TOXENV=docs }

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

notifications:
  email:
    on_success: never
    on_failure: always