language: python
sudo: false
cache: pip
before_install:
  - openssl aes-256-cbc -K $encrypted_12e75a453f27_key -iv $encrypted_12e75a453f27_iv -in gcs-service-account.json.enc -out gcs-service-account.json -d
install:
  - pip install --upgrade setuptools
  - pip install tox-travis
script: tox

jobs:
  fast_finish: true

  include:
    - { name: 'flake8', python: '3.6', env: TOXENV=flake8 }
    - { name: 'py34', python: '3.4', env: TOXENV=py34 }
    - { name: 'py35', python: '3.5', env: TOXENV=py35 }
    - { name: 'py36', python: '3.6', env: TOXENV=py36 }
    - { name: 'py37', python: '3.7', env: TOXENV=py37, dist: xenial, sudo: true }
    - { name: 'docs', python: '3.4', env: TOXENV=docs }
